controller_manager_ns: tangy_moveit_controller_manager
controller_list:
  - name: r_arm_controller_1
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - right_shoulder_x_revolute
  - name: r_arm_controller_2
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - upper_right_arm_z_revolute_joint
  - name: r_arm_controller_3
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - upper_right_arm_y_revolute_joint
  - name: r_arm_controller_4
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - upper_to_lower_right_joint
  - name: r_arm_controller_5
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - wrist_right_arm_z_revolute_joint
  - name: r_arm_controller_6
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - lower_to_wrist_right_arm

  - name: l_arm_controller_1
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - left_shoulder_x_revolute
  - name: l_arm_controller_2
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - upper_left_arm_z_revolute_joint
  - name: l_arm_controller_3
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - upper_left_arm_y_revolute_joint
  - name: l_arm_controller_4
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - upper_to_lower_left_joint
  - name: l_arm_controller_5
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - wrist_left_arm_z_revolute_joint
  - name: l_arm_controller_6
    action_ns: follow_joint_trajectory
    type: "FollowJointTrajectory"
    default: true
    joints: 
      - lower_to_wrist_left_arm
