joint_limits:
  lower_to_wrist_right_arm:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_x_revolute:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  upper_left_arm_z_revolute_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  upper_left_arm_y_revolute_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  upper_to_lower_left_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_left_arm_z_revolute_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lower_to_wrist_left_arm:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_x_revolute:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  upper_right_arm_z_revolute_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  upper_right_arm_y_revolute_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  upper_to_lower_right_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_right_arm_z_revolute_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0