sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /skeleton/openni_depth_frame/depth_registered/points
   max_range: 5.0
   padding_offset: 0
   padding_scale: 1
   frame_subsample: 1
   point_subsample: 1
